### ISSUE TITLE
Create endpoint that returns data as displayed in mobile clients

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#16]
### Todo
- ~~add reference to what is displayed on mobile~~
- ~~create issues for subtasks~~

### Tasks
- [x] Map MultiSig transaction #27 
- [x] Map Ethereum transactions #26 
- [x] Map Module transactions #25 
- [x] Write demo branch in the gnosis/safe-android project consuming the API #44

**Comment by jpalvarezl** [comment]
@rmeissner can we close this one?

**Comment by jpalvarezl** [comment]
All sub tasks are completed.
