### ISSUE TITLE
Add caching via redis

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#17]
### Tasks
- [x] Add redis to service
- [x] Add possibility to enable simple caching (set/ get cache by key with timeout)
- [x] Add possibility to invalidate cache (by key)
