### ISSUE TITLE
Add tests for entry mapping

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#20]
The project should be properly tested. For this we should start with testing the mapping layer

### Tasks
- ~~[ ] Test multisig tx mapping~~
- [x] Test ethereum tx mapping
- [x] Test module tx mapping
- [x] Test unknown mapping
### Notes
- https://stackoverflow.com/questions/38995892/how-to-move-tests-into-a-separate-file-for-binaries-in-rusts-cargo
- https://doc.rust-lang.org/book/ch11-03-test-organization.html#unit-tests
