### ISSUE TITLE
[Staging] Coordinate deployment of interstellar

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-client-gateway#459]
We currently have multiple urls for the different networks. We will have to keep these running for now and change the deployment flow to deploy the unified version to the new url.

### Tasks
- [x] Coordinate with devops that deployments are done to the unified url
- [x] Update deployment doc
- [x] Coordinate with devops how to be able to perform hotfixes on legacy version (with separate network urls)
- [x] Double check webhooks are registered to core services
- [x] Coordinate with the mobile team to define a timeline for deployement

**Comment by jpalvarezl** [comment]
Done:
- Webhooks in dockerhub were adjusted. 
- `interstellar` branch removed after merge to `main`
- Deployements to legacy staging and to current staging verified
