### ISSUE TITLE
[Production] Coordinate deployment of interstellar

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#482]
We currently have multiple urls for the different networks. We will have to keep these running for now and change the deployment flow to deploy the unified version to the new url.

### Tasks
- [x] Coordinate with devops that deployments are done to the unified url
- [x] Update deployment doc
- [x] Coordinate with devops how to be able to perform hotfixes on legacy version (with separate network urls)
~~- [ ] config service webhook~~
- [x] tx service webhooks (mainnet, rinkeby, BSC, polygon, xDai)
- [x] Populate prod instance of the config service with chain info
- [x] Setup new kibana boards (in staging, they need to be imported into prod)
- [x] Coordinate with the mobile team to define a timeline for deployement

**Comment by jpalvarezl** [comment]
Finished as much as possible to this point
