### ISSUE TITLE
Documentation sanity check

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#500]
After substantial changes to our API we should see that `endpoints` , sample `json` , descriptions, etc. are in sync with what we are currently serving: 

Issues causing API changes:
- [x] https://github.com/gnosis/safe-client-gateway/issues/470 (`ETHER` to `NATIVE_COIN`)
- [x] https://github.com/gnosis/safe-client-gateway/issues/484 (`AddressEx` used everywhere)
- [x] https://github.com/gnosis/safe-client-gateway/issues/487 (Introduction of polymorphism to `ExecutionInfo` for `TxSummary`)
- [x] https://github.com/gnosis/safe-client-gateway/issues/490 (change any occurrence of `url` to `uri`)
- [x] https://github.com/gnosis/safe-client-gateway/issues/498 (changed query parameter `page_url` to `cursor`)
