### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-client-gateway#687]
The goal of this issue is to track the progress on our coverage and where we should focus more on.

With https://github.com/gnosis/safe-client-gateway/commit/fad40011aa7e818558c28d835e93db3c1353313f, new tests can be introduced on the route level. This will make it easier to cover more branches with each test.

More specifically we should improve the coverage in the following components:

- [ ] `src/routes/`
  * [ ] `src/routes/balances`
  * [x] `src/routes/chains`
    * [x] PR #769 
  * [x] `src/routes/collectibles`
    * [x] Issue #693  
  * [x] `src/routes/contracts`
    * [x] Issue #693 
  * [ ] `src/routes/delegates`
  * [x] `src/routes/health`
    * [x] PR #731  
  * [ ] `src/routes/hooks`
  * [x] `src/routes/notifications`
    * [x] PR #731 
  * [x] `src/routes/safe_apps`
    * [x] Issue #730 
  * [x] `src/routes/safes`
    * [x] Issue #708  
  * [ ] `src/routes/transactions`
    * [x] `post_confirmation` Issue #679 
    * [x] `get_transactions` Issue #679 (Only `Multisig`)
    * [ ] `get_transactions` Issue #690 (`Module` and  `Ethereum` transactions)
- [x] `src/providers/`
    * [x] Test `info.rs` Issue #689 
    * [x] Test `fiat.rs` Issue #694 
- [ ] `src/monitoring/`
    * [ ] Issue #707  
- [ ] `src/cache`
- [ ] `src/utils`

If you start working on covering a specific path please do create a ticket and link it here.
